<script setup lang="ts">
type Preview = { sourceHash: string; validRowCount: number; errors: Array<{ row: number; message: string }>; rows: Array<{ name: string; category: string; releaseStatus: string }> };
const emit = defineEmits<{ imported: [] }>(); const api = useAdminApi(); const file = shallowRef<File | null>(null); const csv = shallowRef(""); const preview = ref<Preview | null>(null); const loading = shallowRef(false); const message = shallowRef("");
async function choose(event: Event) { const selected = (event.target as HTMLInputElement).files?.[0]; if (!selected) return; file.value = selected; csv.value = await selected.text(); preview.value = null; message.value = ""; }
async function validate() { if (!file.value || !csv.value) return; loading.value = true; message.value = ""; try { preview.value = await api<Preview>("/v1/events/imports/preview", { method: "POST", body: { contractVersion: "1", fileName: file.value.name, csv: csv.value } }); } catch (error: any) { message.value = error?.data?.error?.message ?? "无法预检文件。"; } finally { loading.value = false; } }
async function submit() { if (!file.value || !preview.value || preview.value.errors.length) return; loading.value = true; try { const result = await api<{ importedCount: number }>("/v1/events/imports", { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: { contractVersion: "1", fileName: file.value.name, csv: csv.value } }); message.value = `已导入 ${result.importedCount} 条事件。`; preview.value = null; emit("imported"); } catch (error: any) { message.value = error?.data?.error?.message ?? "导入失败。"; } finally { loading.value = false; } }
</script>
<template><section class="import-panel"><div><p class="eyebrow">一次性导入</p><h2>从飞书 CSV 导入</h2><p>先预检，再确认写入；文件不会被保存。</p></div><div class="import-actions"><input type="file" accept=".csv,text/csv" aria-label="选择 CSV 文件" @change="choose" /><UButton label="预检文件" color="neutral" variant="outline" :loading="loading" :disabled="!file" @click="validate" /></div><p v-if="message" class="message">{{ message }}</p><div v-if="preview" class="preview"><strong>{{ preview.errors.length ? `发现 ${preview.errors.length} 个问题` : `可导入 ${preview.validRowCount} 条事件` }}</strong><ul v-if="preview.errors.length"><li v-for="error in preview.errors" :key="`${error.row}-${error.message}`">第 {{ error.row }} 行：{{ error.message }}</li></ul><div v-else class="preview-rows"><span v-for="row in preview.rows" :key="row.name">{{ row.name }} · {{ row.category }}</span></div><UButton v-if="!preview.errors.length" label="确认导入" :loading="loading" @click="submit" /></div></section></template>
<style scoped>.import-panel { display:grid; gap:14px; padding:20px; border:1px solid var(--line); border-radius:14px; background:color-mix(in oklch,var(--surface-raised) 88%,transparent); }.import-panel h2 { margin:2px 0 0; font-size:1.2rem; letter-spacing:-.03em; }.import-panel p { margin:5px 0 0; color:var(--quiet); font-size:.83rem; }.import-actions { display:flex; flex-wrap:wrap; align-items:center; gap:10px; }.message { color:var(--accent)!important; }.preview { display:grid; gap:10px; padding-top:14px; border-top:1px solid var(--line); font-size:.82rem; }.preview ul { margin:0; padding-left:18px; color:var(--quiet); }.preview-rows { display:flex; flex-wrap:wrap; gap:6px; color:var(--quiet); }.preview-rows span { padding:4px 7px; border-radius:7px; background:var(--surface); } @media (prefers-reduced-transparency: reduce) { .import-panel { background:var(--surface-raised); } }</style>
