<script setup lang="ts">
import type { RandomEvent } from "~/types/random-event";

const props = defineProps<{ events: RandomEvent[] }>();
const query = shallowRef("");
const category = shallowRef("all");
const rarity = shallowRef("all");
const selected = shallowRef<RandomEvent | null>(null);
const categories = computed(() => [...new Set(props.events.map((event) => event.category))].sort());
const rarities = computed(() => [...new Set(props.events.map((event) => event.rarity))].sort());
const visibleEvents = computed(() => props.events.filter((event) => (category.value === "all" || event.category === category.value) && (rarity.value === "all" || event.rarity === rarity.value) && (!query.value.trim() || `${event.name}${event.description}`.includes(query.value.trim()))));
const detailOpen = computed({ get: () => selected.value !== null, set: (open) => { if (!open) selected.value = null; } });
const statusText = (status: RandomEvent["releaseStatus"]) => status === "implemented" ? "已实装" : "已移除";
</script>

<template>
  <section class="event-directory" aria-label="随机事件目录">
    <div class="filters"><UInput v-model="query" placeholder="搜索事件" aria-label="搜索事件" /><USelect v-model="category" :items="[{ label: '全部类别', value: 'all' }, ...categories.map((value) => ({ label: value, value }))]" aria-label="筛选事件类别" /><USelect v-model="rarity" :items="[{ label: '全部稀有度', value: 'all' }, ...rarities.map((value) => ({ label: value, value }))]" aria-label="筛选事件稀有度" /></div>
    <div v-if="visibleEvents.length" class="event-grid"><button v-for="event in visibleEvents" :key="event.eventId" class="event-card" type="button" @click="selected = event"><div class="card-top"><span class="event-rarity">{{ event.rarity }}</span><StatusBadge :label="statusText(event.releaseStatus)" :tone="event.releaseStatus === 'implemented' ? 'success' : 'warning'" /></div><h2>{{ event.name }}</h2><p>{{ event.description }}</p><div class="event-tags"><UBadge v-for="tag in event.effectTags" :key="tag" :label="tag" color="neutral" variant="subtle" /></div></button></div>
    <UEmpty v-else title="暂无事件" description="没有符合当前筛选条件的事件。" variant="naked" />
    <UModal v-model:open="detailOpen" :title="selected?.name ?? '事件详情'" :description="selected ? `${selected.category} · 版本 ${selected.gameVersion}` : undefined" :ui="{ content: 'max-w-2xl' }"><template #body><div v-if="selected" class="detail"><p class="description">{{ selected.description }}</p><dl><div><dt>稀有度</dt><dd>{{ selected.rarity }}</dd></div><div><dt>持续时间</dt><dd>{{ selected.durationSeconds === null ? '暂无记录' : `${selected.durationSeconds} 秒` }}</dd></div><div><dt>内置冷却</dt><dd>{{ selected.cooldownSeconds === null ? '暂无记录' : `${selected.cooldownSeconds} 秒` }}</dd></div><div><dt>权重</dt><dd>{{ selected.weight ?? '暂无记录' }}</dd></div><div><dt>出现概率</dt><dd>{{ selected.appearanceProbability === null ? '暂无记录' : `${(selected.appearanceProbability * 100).toFixed(2)}%` }}</dd></div></dl><div class="event-tags"><UBadge v-for="tag in selected.effectTags" :key="tag" :label="tag" color="neutral" variant="subtle" /></div><section class="challenges"><h3>开放挑战</h3><p v-if="!selected.challenges.length" class="muted">暂无开放挑战。</p><NuxtLink v-for="challenge in selected.challenges" :key="challenge.challengeId" to="/achievements" class="challenge-link">{{ challenge.family === 'map' ? challenge.name : challenge.titleName }}<span>查看成就 →</span></NuxtLink></section></div></template></UModal>
  </section>
</template>

<style scoped>
.event-directory { display: grid; gap: 22px; }.filters { display: grid; grid-template-columns: minmax(0, 1fr) 160px 160px; gap: 10px; }.event-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 13px; }.event-card { display: grid; min-height: 210px; align-content: start; gap: 13px; padding: 18px; border: 1px solid var(--line); border-radius: 14px; color: var(--text); background: color-mix(in oklch, var(--surface-raised) 88%, transparent); cursor: pointer; text-align: left; transition: transform 180ms ease, box-shadow 180ms ease, border-color 180ms ease; }.event-card:hover, .event-card:focus-visible { border-color: var(--line-strong); box-shadow: 0 14px 26px -22px var(--shadow); transform: translateY(-2px); }.event-card:active { transform: scale(.985); transition-duration: 90ms; }.card-top { display:flex; align-items:center; justify-content:space-between; gap:8px; }.event-rarity { color:var(--accent); font-size:.72rem; font-weight:750; letter-spacing:.06em; }.event-card h2 { margin:0; font-size:1.08rem; letter-spacing:-.035em; }.event-card p { display:-webkit-box; margin:0; overflow:hidden; color:var(--quiet); font-size:.84rem; line-height:1.55; -webkit-box-orient:vertical; -webkit-line-clamp:3; }.event-tags { display:flex; flex-wrap:wrap; gap:6px; }.detail { display:grid; gap:18px; }.description { margin:0; color:var(--text); line-height:1.65; }.detail dl { display:grid; grid-template-columns:repeat(2,1fr); gap:0; margin:0; border-top:1px solid var(--line); }.detail dl div { display:flex; justify-content:space-between; gap:10px; padding:11px 0; border-bottom:1px solid var(--line); }.detail dl div:nth-child(odd) { padding-right:16px; }.detail dt { color:var(--muted); font-size:.8rem; }.detail dd { margin:0; font-size:.82rem; font-weight:650; }.challenges { display:grid; gap:8px; }.challenges h3 { margin:0; font-size:1rem; }.challenge-link { display:flex; justify-content:space-between; gap:12px; padding:12px; border-radius:10px; color:var(--text); background:var(--surface); text-decoration:none; }.challenge-link span,.muted { color:var(--quiet); font-size:.8rem; }
@media (max-width:760px) { .filters { grid-template-columns:1fr 1fr; }.filters > :first-child { grid-column:1 / -1; }.event-grid { grid-template-columns:repeat(2,minmax(0,1fr)); } } @media (max-width:520px) { .event-grid { grid-template-columns:1fr; }.detail dl { grid-template-columns:1fr; }.detail dl div:nth-child(odd) { padding-right:0; } } @media (prefers-reduced-motion: reduce) { .event-card { transition: opacity 150ms ease; }.event-card:hover { transform:none; } } @media (prefers-reduced-transparency: reduce) { .event-card { background:var(--surface-raised); } }
</style>
