packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true

minimumReleaseAgeExclude:
  - '@nuxt/ui'
  - miniflare
  - wrangler

patchedDependencies:
  nuxt-studio@1.7.0: patches/nuxt-studio@1.7.0.patch
