CREATE TABLE effect_glossary_terms (
  key TEXT PRIMARY KEY NOT NULL,
  name_zh TEXT NOT NULL,
  aliases_json TEXT NOT NULL DEFAULT '[]',
  category TEXT NOT NULL,
  summary TEXT NOT NULL,
  definition TEXT NOT NULL,
  rules_json TEXT NOT NULL DEFAULT '[]',
  source_version TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE INDEX effect_glossary_terms_name_idx ON effect_glossary_terms (name_zh);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('PASSIVE_SELF_HEAL', '脱战自动回复', '["脱战自动回复（被动）","自我治疗"]', '被动', '连续 3 秒未再受伤后开始自动恢复生命值。', '受到伤害会刷新计时；连续 3 秒未再受伤时开始自我治疗，每秒恢复 50 + 8% 最大生命值。死亡、满血或禁疗时不会触发；再次受伤会打断并重新计时。', '["可与游戏本体的自我恢复被动叠加生效。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('HEALING', '治疗效果', '["治疗","受到治疗","生命恢复","造成治疗"]', '状态', '所有受到或造成的治疗都属于治疗效果。', '治疗效果包含治疗、受到治疗、生命恢复与造成治疗。该词条统一覆盖所有“恢复生命值”的效果来源。', '["随机事件中的非唯一治疗效果可与英雄技能治疗叠加。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('INVULNERABLE', '无敌', '["伤害免疫","免疫伤害","无敌状态"]', '增益效果/状态', '使目标免疫所有伤害。', '伤害免疫（无敌）是一种状态效果，能使目标免疫所有伤害。攻击仍会命中目标，但其造成的伤害将被抵消。进入无敌状态还能阻止（但不会移除）击晕、击倒和睡眠效果。', '["无敌默认不会清除已存在的负面状态。","多数带无敌的技能会同时附加净化效果。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('PHASE_SHIFT', '相移', '["消散","相移状态"]', '增益效果/状态', '使英雄无法被命中并免疫大多数负面效果。', '相移使英雄免疫伤害及大多数负面效果。处于相移脱离状态的英雄可穿透其他玩家，且不会被敌方攻击命中。与“无敌”状态不同，相移并非仅“格挡”伤害，而是从根本上无法被击中，所有弹道类攻击都将直接穿过英雄身体。', '["相移生效时通常会触发净化机制。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('CLEANSE', '净化', '["清除负面状态"]', '增益效果/状态', '移除可净化状态并赋予短暂保护。', '净化会移除可净化（随机事件附加的效果除外）的状态效果。净化会使目标同时获得无敌与相移状态，目前只有雾子的铃可以施加这个效果。', '["击倒状态下净化无效。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('DAMAGE_REDUCTION', '伤害减免', '["减伤"]', '增益效果/状态', '降低受到的伤害。', '伤害减免会按百分比降低目标最终受到的伤害，是随机事件与英雄技能常见的防御乘区。', '["随机事件减伤可与英雄技能减伤叠加乘算。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('MOVE_SPEED_BOOST', '移动速度加成', '["移速加成","移速增益","移动速度提高"]', '增益效果/状态', '按基础移动速度的百分比提升水平移速。', '移动速度加成效果是指以英雄基础移动速度为基准，按百分比提高其水平移动速度。', '["随机事件移速加成无叠加上限，可与英雄技能加速乘算。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('HEALING_BOOST', '增疗', '["治疗强度","受治疗强度"]', '增益效果/状态', '按百分比增加造成和受到的治疗。', '增疗会按百分比增加造成与受到的治疗，是对治疗结果的正向乘算修正。', '["随机事件增疗可与英雄技能增疗叠加乘算。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('KNOCKBACK_RESIST', '击退抵抗', '["击退抗性"]', '增益效果/状态', '按百分比降低受到的击退效果。', '击退抵抗会按百分比降低受到的击退效果，减少冲击力导致的推离距离。', '["随机事件击退抵抗可与英雄技能击退抵抗叠加乘算。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('STUN', '击晕', '["眩晕"]', '负面状态', '完全阻止玩家控制英雄。', '击晕是一种负面状态效果，会完全阻止玩家控制其英雄。被击晕的英雄无法移动、射击、瞄准或使用技能。此外，受到击晕会打断移动类技能以及具有短暂施法前摇或需要引导的技能。', '["被打断技能通常进入完整冷却。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('KNOCKDOWN', '击倒', '["倒地"]', '负面状态', '效果类似击晕并附带倒地状态。', '击倒对目标英雄产生的效果与击晕相同，但还会使英雄倒地仰卧。在持续时间最后 0.5 秒内，目标将进入起身动画并开始站立。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('SLEEP', '麻醉', '["沉睡","睡眠"]', '负面状态', '类似击倒，但受伤会提前苏醒。', '麻醉与击倒效果相似，但不同之处在于目标受到伤害时会立即开始苏醒动画。目前唯一能造成麻醉效果的技能是安娜的睡眠镖。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('FREEZE', '冰冻', '[]', '负面状态', '类似击晕的独特控制状态。', '冰冻是一种独特的类似击晕效果，其产生的效果与击晕完全相同。区别在于该状态可通过使目标无敌的效果解除，例如投射屏障。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('KNOCKBACK', '击退', '[]', '负面状态', '对目标施加冲击并强制位移。', '击退是一种产生冲击力、强制移动英雄的效果。多种技能及大多数爆炸性武器均可施加击退效果，多数英雄标配的快速近战攻击也会造成小幅击退。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('SLOW', '减速', '[]', '负面状态', '降低目标移动速度。', '减速是一种负面状态效果，会降低目标移动速度。由敌人施加的减速强度会相互叠加，并与移动速度增益共存。自我施加的移动速度惩罚不会与其他减速叠加，两者中仅取减速幅度最大者生效。', '["部分位移技能不受减速影响。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('VULNERABLE', '易伤', '["受到的伤害","伤害增幅"]', '负面状态', '提高目标承受伤害。', '易伤会使目标在被标记期间承受更多伤害，属于提高承伤的负面乘区。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('HEAL_REDUCTION', '减疗', '["减少治疗","降低治疗"]', '负面状态', '按百分比减少造成和受到的治疗。', '减疗会按百分比减少造成与受到的治疗，直接降低治疗链路的最终结算量。', '["随机事件减疗可与英雄技能减疗叠加乘算。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('HEAL_BLOCK', '禁疗', '[]', '负面状态', '无法受到任何治疗与生命恢复。', '处于禁疗时所有治疗和生命恢复都失效。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('DOT', '持续伤害', '["DoT","Damage over time"]', '负面状态', '周期性造成伤害，不依赖后续交互。', '持续伤害（DoT / Damage over time）会使玩家在无需与其他人进一步互动的情况下，周期性受到伤害，且不受目标英雄位置影响。', '["随机事件施加的持续伤害无法被相移、无敌、净化或治疗包解除。","持续伤害来源攻击会无视护甲。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('BURNING', '燃烧', '["点燃"]', '负面状态', '附带持续伤害的负面状态。', '燃烧（点燃）是一种附带持续伤害效果的负面状态，持续期间会稳定造成 DoT 伤害。', '["随机事件燃烧无法被相移、无敌、净化或治疗包解除。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('PERMANENT_EFFECT', '永久', '["永久效果"]', '随机事件', '事件提供的永久收益，不会随事件结束失效。', '来自于事件的永久效果，不会随事件结束、英雄切换而失去效果。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('TEMPORARY_EFFECT', '临时', '["临时效果"]', '随机事件', '事件提供的短时效果，通常会失效。', '来自于事件的短暂、临时效果，一般会随事件结束、英雄切换或在事件持续期间内失去效果。大多数事件效果都属于临时效果。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('MAX_HEALTH', '最大生命值', '[]', '随机事件', '生命值条的上限总量。', '最大生命值是玩家生命值条的总量。当前生命值可能会因伤害而消耗，并通过治疗恢复，但不会超过最大生命值属性的总量。', '["随机事件语境下指当前效果主体（事件玩家）的最大生命值。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('HEART_OF_STEEL', '心之钢', '["心之钢层数"]', '随机事件', '通过层数永久提升最大生命值百分比。', '随机事件中的特殊效果：通过获得“心之钢层数”来永久提升玩家最大生命值百分比。每层心之钢使最大生命值百分比提高 0.75%。', '["不是按当前血量高低叠层。","每层提供固定百分比提升。"]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('HEALTH_LOSS', '生命值损耗', '[]', '随机事件', '一种可被减伤与护甲影响的伤害。', '生命值损耗属于伤害效果，可被护甲、伤害减免等机制降低。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('EVENT_ROLL', '幸运值', '[]', '随机事件', '玩家抽取到事件的概率', '玩家抽取到事件的概率，范围为 0-100。', '[]', 'v1', 1780000000000);
INSERT INTO effect_glossary_terms (key, name_zh, aliases_json, category, summary, definition, rules_json, source_version, updated_at) VALUES ('EXECUTE', '斩杀', '[]', '随机事件', '无视增益效果直接击杀。', '斩杀会无视玩家当前增益效果，直接将其击杀。', '[]', 'v1', 1780000000000);
