<script setup lang="ts">
import type { RandomEvent } from "~/types/random-event";
import EventVersionDirectory from "~/components/events/EventVersionDirectory.vue";
useSeoMeta({ title: "随机事件 · 躲避堡垒 3", description: "查看当前随机事件与开放挑战。" });
type EventVersion = { gameVersion: string; eventCount: number };
const api = usePortalApi(); const versions = ref<EventVersion[]>([]); const eventsByVersion = ref<Record<string, RandomEvent[]>>({}); const loading = shallowRef(true); const error = shallowRef(false); const loadingVersion = shallowRef<string | null>(null); const failedVersion = shallowRef<string | null>(null);
async function loadVersion(gameVersion: string) { if (eventsByVersion.value[gameVersion] || loadingVersion.value) return; loadingVersion.value = gameVersion; failedVersion.value = null; try { eventsByVersion.value = { ...eventsByVersion.value, [gameVersion]: (await api<{ items: RandomEvent[] }>(`/v1/events?version=${encodeURIComponent(gameVersion)}`)).items }; } catch { failedVersion.value = gameVersion; } finally { loadingVersion.value = null; } }
onMounted(async () => { try { versions.value = (await api<{ items: EventVersion[] }>("/v1/events/versions")).items; if (versions.value[0]) await loadVersion(versions.value[0].gameVersion); } catch { error.value = true; } finally { loading.value = false; } });
</script>
<template><main class="events-page page-shell"><section class="page-intro"><h1 class="page-title">随机事件</h1><p class="body-copy">查看已实装事件、历史记录与开放挑战。</p></section><section class="events-panel surface-card"><p v-if="loading" class="state">读取中…</p><UAlert v-else-if="error" color="error" variant="subtle" title="无法读取事件" description="请稍后重试。" /><EventVersionDirectory v-else :versions="versions" :events-by-version="eventsByVersion" :loading-version="loadingVersion" :failed-version="failedVersion" @load-version="loadVersion" /></section></main></template>
<style scoped>.events-page { padding-block:clamp(64px,9vh,104px) 72px; }.page-intro { margin-bottom:32px; }.events-panel { padding:clamp(18px,4vw,36px); }.state { padding:100px 0; color:var(--muted); text-align:center; } @media (max-width:620px) { .events-page { padding-block:48px; }.page-intro { margin-bottom:20px; }.events-panel { padding:14px; } }</style>
